### PR TITLE
produce bom in CycloneDX format

### PR DESCRIPTION
**Pull request by lluan444**

### CODE REVIEW

**Comment by nadgowdas** [comment]
Can you post sample cycloneDX output here and the schema mapping that's followed? Thanks

**Comment by lluan444** [comment]
the output for [discovery dockerfile](https://github.ibm.com/oneibmcloud/gitsecure-discovery/blob/main/Dockerfile): 

```
{
  "bomFormat": "CycloneDX",
  "specVersion": "1.3",
  "version": 1,
  "metadata": {
    "component": {
      "bom-ref": "image:lauratest/discovery:test@index.docker.io/lauratest/discovery@sha256:9b9e09122217e6a1923399048706bdca2a99c2ee4a7b3a5034ad8d93b0ace78c",
      "type": "container",
      "name": "lauratest/discovery:test",
      "version": "index.docker.io/lauratest/discovery@sha256:9b9e09122217e6a1923399048706bdca2a99c2ee4a7b3a5034ad8d93b0ace78c"
    },
    "properties": [
      {
        "name": "internal:scan-timestamp",
        "value": "2022-01-12 14:35:13.562188765 +0000 UTC m=+38.717128200"
      }
    ]
  },
  "components": [
    {
      "bom-ref": "image:index.docker.io/lauratest/discovery@sha256:9b9e09122217e6a1923399048706bdca2a99c2ee4a7b3a5034ad8d93b0ace78c",
      "type": "container",
      "name": "lauratest/discovery:test",
      "version": "",
      "purl": "index.docker.io/lauratest/discovery@sha256:9b9e09122217e6a1923399048706bdca2a99c2ee4a7b3a5034ad8d93b0ace78c",
      "components": [
        {
          "bom-ref": "file:/etc/yum.repos.d/adoptopenjdk11-openj9.repo",
          "type": "file",
          "supplier": {
            "name": "",
            "url": [
              "github.com/gitsecure-discovery"
            ]
          },
          "group": "github.com/gitsecure-discovery",
          "name": "adoptopenjdk11-openj9.repo",
          "version": "cde655b653a380b7857d369e07700e2fead22c43d3e0668885fd09454207ffd8",
          "hashes": [
            {
              "alg": "SHA-256",
              "content": "cde655b653a380b7857d369e07700e2fead22c43d3e0668885fd09454207ffd8"
            }
          ]
        },
        {
          "type": "application",
          "supplier": {
            "name": "",
            "url": [
              "https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64"
            ]
          },
          "name": "github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64",
          "version": "",
          "purl": "https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64",
          "components": [
            {
              "bom-ref": "file:/tmp/build-ctx026471399/rootfs/jq",
              "type": "file",
              "supplier": {
                "name": "",
                "url": [
                  "https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64"
                ]
              },
              "group": "github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64",
              "name": "jq",
              "version": "af986793a515d500ab2d35f8d2aecd656e764504b789b66d7e1a0b727a124c44",
              "hashes": [
                {
                  "alg": "SHA-256",
                  "content": "af986793a515d500ab2d35f8d2aecd656e764504b789b66d7e1a0b727a124c44"
                }
              ]
            },
            {
              "bom-ref": "file:/tmp/build-ctx026471399/rootfs/usr/bin/jq",
              "type": "file",
              "supplier": {
                "name": "",
                "url": [
                  "https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64"
                ]
              },
              "group": "github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64",
              "name": "jq",
              "version": "af986793a515d500ab2d35f8d2aecd656e764504b789b66d7e1a0b727a124c44",
              "hashes": [
                {
                  "alg": "SHA-256",
                  "content": "af986793a515d500ab2d35f8d2aecd656e764504b789b66d7e1a0b727a124c44"
                }
              ]
            }
          ]
        },
        {
          "type": "application",
          "supplier": {
            "name": "",
            "url": [
              "https://download.clis.cloud.ibm.com/ibm-cloud-cli/1.2.0/IBM_Cloud_CLI_1.2.0_amd64.tar.gz"
            ]
          },
          "name": "download.clis.cloud.ibm.com/ibm-cloud-cli/1.2.0/IBM_Cloud_CLI_1.2.0_amd64.tar.gz",
          "version": "",
          "purl": "https://download.clis.cloud.ibm.com/ibm-cloud-cli/1.2.0/IBM_Cloud_CLI_1.2.0_amd64.tar.gz",
          "components": [
            {
              "bom-ref": "file:/tmp/build-ctx026471399/rootfs/usr/local/bin/ibmcloud",
              "type": "file",
              "supplier": {
                "name": "",
                "url": [
                  "https://download.clis.cloud.ibm.com/ibm-cloud-cli/1.2.0/IBM_Cloud_CLI_1.2.0_amd64.tar.gz"
                ]
              },
              "group": "download.clis.cloud.ibm.com/ibm-cloud-cli/1.2.0/IBM_Cloud_CLI_1.2.0_amd64.tar.gz",
              "name": "ibmcloud",
              "version": "832ce627b3048b1ff31a79f1673e98e539ace6d6d42f1cfd6d5d641cda6941ca",
              "hashes": [
                {
                  "alg": "SHA-256",
                  "content": "832ce627b3048b1ff31a79f1673e98e539ace6d6d42f1cfd6d5d641cda6941ca"
                }
              ]
            }
          ]
        },
        {
          "type": "application",
          "supplier": {
            "name": "",
            "url": [
              "https://mirrors.ocf.berkeley.edu/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz"
            ]
          },
          "name": "mirrors.ocf.berkeley.edu/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz",
          "version": "",
          "purl": "https://mirrors.ocf.berkeley.edu/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz",
          "components": [
            {
              "type": "application",
              "supplier": {
                "name": "",
                "url": [
                  "https://mirrors.ocf.berkeley.edu/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz"
                ]
              },
              "group": "mirrors.ocf.berkeley.edu/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz",
              "name": "maven",
              "version": "",
              "hashes": [],
              "purl": "https://mirrors.ocf.berkeley.edu/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz"
            }
          ]
        },
        {
          "type": "application",
          "supplier": {
            "name": "",
            "url": [
              "https://services.gradle.org/distributions/gradle-6.8-bin.zip"
            ]
          },
          "name": "services.gradle.org/distributions/gradle-6.8-bin.zip",
          "version": "",
          "purl": "https://services.gradle.org/distributions/gradle-6.8-bin.zip",
          "components": [
            {
              "bom-ref": "file:/tmp/build-ctx026471399/rootfs/gradle-6.8-bin.zip",
              "type": "file",
              "supplier": {
                "name": "",
                "url": [
                  "https://services.gradle.org/distributions/gradle-6.8-bin.zip"
                ]
              },
              "group": "services.gradle.org/distributions/gradle-6.8-bin.zip",
              "name": "gradle-6.8-bin.zip",
              "version": "e2774e6fb77c43657decde25542dea710aafd78c4022d19b196e7e78d79d8c6c",
              "hashes": [
                {
                  "alg": "SHA-256",
                  "content": "e2774e6fb77c43657decde25542dea710aafd78c4022d19b196e7e78d79d8c6c"
                }
              ]
            },
            {
              "type": "application",
              "supplier": {
                "name": "",
                "url": [
                  "https://services.gradle.org/distributions/gradle-6.8-bin.zip"
                ]
              },
              "group": "services.gradle.org/distributions/gradle-6.8-bin.zip",
              "name": "gradle",
              "version": "",
              "hashes": [],
              "purl": "https://services.gradle.org/distributions/gradle-6.8-bin.zip"
            }
          ]
        },
        {
          "type": "application",
          "supplier": {
            "name": "",
            "url": [
              "https://download.docker.com/linux/static/stable/x86_64/docker-19.03.0.tgz"
            ]
          },
          "name": "download.docker.com/linux/static/stable/x86_64/docker-19.03.0.tgz",
          "version": "",
          "purl": "https://download.docker.com/linux/static/stable/x86_64/docker-19.03.0.tgz",
          "components": [
            {
              "bom-ref": "file:/tmp/build-ctx026471399/rootfs/tmp/docker-19.03.0.tgz",
              "type": "file",
              "supplier": {
                "name": "",
                "url": [
                  "https://download.docker.com/linux/static/stable/x86_64/docker-19.03.0.tgz"
                ]
              },
              "group": "download.docker.com/linux/static/stable/x86_64/docker-19.03.0.tgz",
              "name": "docker-19.03.0.tgz",
              "version": "b7bb0c3610b3f6ee87457dfb440968dbcc3537198c3d6e2468fcf90819855d6f",
              "hashes": [
                {
                  "alg": "SHA-256",
                  "content": "b7bb0c3610b3f6ee87457dfb440968dbcc3537198c3d6e2468fcf90819855d6f"
                }
              ]
            },
            {
              "bom-ref": "file:/tmp/build-ctx026471399/rootfs/usr/local/bin/docker",
              "type": "file",
              "supplier": {
                "name": "",
                "url": [
                  "https://download.docker.com/linux/static/stable/x86_64/docker-19.03.0.tgz"
                ]
              },
              "group": "download.docker.com/linux/static/stable/x86_64/docker-19.03.0.tgz",
              "name": "docker",
              "version": "b5b8be0ef379ea1460cc27871c96a969319f131fa389bf25be0279a09f785c17",
              "hashes": [
                {
                  "alg": "SHA-256",
                  "content": "b5b8be0ef379ea1460cc27871c96a969319f131fa389bf25be0279a09f785c17"
                }
              ]
            }
          ]
        },
        {
          "type": "application",
          "supplier": {
            "name": "",
            "url": [
              "https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl\""
            ]
          },
          "name": "storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl\"",
          "version": "",
          "purl": "https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl\"",
          "components": [
            {
              "bom-ref": "file:/tmp/build-ctx026471399/rootfs/usr/bin/kubectl",
              "type": "file",
              "supplier": {
                "name": "",
                "url": [
                  "https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl\""
                ]
              },
              "group": "storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl\"",
              "name": "kubectl",
              "version": "78178a8337fc6c76780f60541fca7199f0f1a2e9c41806bded280a4a5ef665c9",
              "hashes": [
                {
                  "alg": "SHA-256",
                  "content": "78178a8337fc6c76780f60541fca7199f0f1a2e9c41806bded280a4a5ef665c9"
                }
              ]
            }
          ]
        },
        {
          "type": "application",
          "supplier": {
            "name": "",
            "url": [
              "https://bootstrap.pypa.io/pip/2.7/get-pip.py"
            ]
          },
          "name": "bootstrap.pypa.io/pip/2.7/get-pip.py",
          "version": "",
          "purl": "https://bootstrap.pypa.io/pip/2.7/get-pip.py",
          "components": [
            {
              "bom-ref": "file:/tmp/build-ctx026471399/rootfs/get-pip.py",
              "type": "file",
              "supplier": {
                "name": "",
                "url": [
                  "https://bootstrap.pypa.io/pip/2.7/get-pip.py"
                ]
              },
              "group": "bootstrap.pypa.io/pip/2.7/get-pip.py",
              "name": "get-pip.py",
              "version": "40ee07eac6674b8d60fce2bbabc148cf0e2f1408c167683f110fd608b8d6f416",
              "hashes": [
                {
                  "alg": "SHA-256",
                  "content": "40ee07eac6674b8d60fce2bbabc148cf0e2f1408c167683f110fd608b8d6f416"
                }
              ]
            }
          ]
        },
        {
          "bom-ref": "file:/usr/local/bin/discovery",
          "type": "file",
          "supplier": {
            "name": "",
            "url": [
              "buildstage:go-lib:/usr/local/bin/discovery"
            ]
          },
          "group": "buildstage:go-lib:/usr/local/bin/discovery",
          "name": "discovery",
          "version": "fa108a3f86f30c6b702576bdb23d4973ff53f12b6c8640027c0ddea4f39fdb3b",
          "hashes": [
            {
              "alg": "SHA-256",
              "content": "fa108a3f86f30c6b702576bdb23d4973ff53f12b6c8640027c0ddea4f39fdb3b"
            }
          ]
        },
        {
          "bom-ref": "file:/LICENSE.txt",
          "type": "file",
          "supplier": {
            "name": "",
            "url": [
              "github.com/gitsecure-discovery"
            ]
          },
          "group": "github.com/gitsecure-discovery",
          "name": "LICENSE.txt",
          "version": "72fc6d84e9b1a939bc69d03b7afeec0369a87a2c6c3044adff8707774ec30027",
          "hashes": [
            {
              "alg": "SHA-256",
              "content": "72fc6d84e9b1a939bc69d03b7afeec0369a87a2c6c3044adff8707774ec30027"
            }
          ]
        },
        {
          "bom-ref": "file:/NON_IBM_LICENSE.txt",
          "type": "file",
          "supplier": {
            "name": "",
            "url": [
              "github.com/gitsecure-discovery"
            ]
          },
          "group": "github.com/gitsecure-discovery",
          "name": "NON_IBM_LICENSE.txt",
          "version": "e9cca0f789c928707dd7dca08af2273763063f0f01b9d66ba6c148b40d1f933c",
          "hashes": [
            {
              "alg": "SHA-256",
              "content": "e9cca0f789c928707dd7dca08af2273763063f0f01b9d66ba6c148b40d1f933c"
            }
          ]
        },
        {
          "bom-ref": "file:/NOTICES.txt",
          "type": "file",
          "supplier": {
            "name": "",
            "url": [
              "github.com/gitsecure-discovery"
            ]
          },
          "group": "github.com/gitsecure-discovery",
          "name": "NOTICES.txt",
          "version": "f0117f4898b7ef7941ac22c7603e9d76c49210708ee6cd72dc6125dd121e9592",
          "hashes": [
            {
              "alg": "SHA-256",
              "content": "f0117f4898b7ef7941ac22c7603e9d76c49210708ee6cd72dc6125dd121e9592"
            }
          ]
        },
        {
          "bom-ref": "file:/etc/gitsecure/scripts/xml2json.js",
          "type": "file",
          "supplier": {
            "name": "",
            "url": [
              "github.com/gitsecure-discovery"
            ]
          },
          "group": "github.com/gitsecure-discovery",
          "name": "xml2json.js",
          "version": "d7e2f7f1dc9d87d7ebe21f4e0f9363a2f9127ace6d5d21bad3d2b0be98a67088",
          "hashes": [
            {
              "alg": "SHA-256",
              "content": "d7e2f7f1dc9d87d7ebe21f4e0f9363a2f9127ace6d5d21bad3d2b0be98a67088"
            }
          ]
        }
      ]
    }
  ]
}

```

**Comment by nadgowdas** [comment]
thanks @lluan444 can we define what we consider `application` and `file` ?

**Comment by lluan444** [comment]
@nadgowdas I have not found clear definitions on Cyclone website for Application. The following is what I think.

- An Application could be an executable file or a directory of files with some of them executable. 
- A File is a file that may or may not be executable. For BOM accuracy one may limit File to be non-executable only.

Currently the code does not parse the file/directory to identify if they are executable. It simply treats a directory and the files in it as a Application Component, and single files that are not contained in the directory as a File Component. We can improve code to accurately reflect how we define them.

**Comment by nadgowdas** [comment]
thanks @lluan444 
@mrutkows can you please help review the schema above?

**Pull request merged**
